export const theme = {
  primary: '#48dbfb',
  secondary: '#48dbfb',
  background: '#080808',
  textLight: '#fafafa',
  textDark: '#bdbdbd',
  maxWidth: '1300px',
  secondaryFont: `'Orbitron', sans-serif`,
  textFont: `'Montserrat', sans-serif`,
  breakpoints: {
    mobile: 'screen and (min-width:370px)',
    xsm: 'screen and (min-width:411px)',
    sm: 'screen and (min-width:540px)',
    md: 'screen and (min-width:768px)',
    lg: 'screen and (min-width:1024px)',
    xl: 'screen and (min-width:1200px)',
    xxl: 'screen and (min-width:1536px)',
    fullhd: 'screen and (min-width:1920px)',
  },
};
